[package]
name = "zad1"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.139"
